version: '3'

services:
  database-service:
    restart: always
    image: mysql
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: Test12345
      MYSQL_DATABASE: finance_kafka_test
#    volumes:
#      - dbdata:/var/lib/mysql
  allocator-service:
    restart: on-failure
    build: .\allocator-service-ms
    ports:
      - 8085:8085
    environment:
      spring.datasource.url: jdbc:mysql://database-service:3306/finance_kafka_test?characterEncoding=utf8&serverTimezone=CET&createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root
#volumes:
#  dbdata:
